// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: ctrl.proto

package ctrlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Op int32

const (
	Op_QUERY Op = 0
	Op_JOIN  Op = 1
	Op_LEAVE Op = 2
	Op_MOVE  Op = 3
)

// Enum value maps for Op.
var (
	Op_name = map[int32]string{
		0: "QUERY",
		1: "JOIN",
		2: "LEAVE",
		3: "MOVE",
	}
	Op_value = map[string]int32{
		"QUERY": 0,
		"JOIN":  1,
		"LEAVE": 2,
		"MOVE":  3,
	}
)

func (x Op) Enum() *Op {
	p := new(Op)
	*p = x
	return p
}

func (x Op) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Op) Descriptor() protoreflect.EnumDescriptor {
	return file_ctrl_proto_enumTypes[0].Descriptor()
}

func (Op) Type() protoreflect.EnumType {
	return &file_ctrl_proto_enumTypes[0]
}

func (x Op) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Op.Descriptor instead.
func (Op) EnumDescriptor() ([]byte, []int) {
	return file_ctrl_proto_rawDescGZIP(), []int{0}
}

type Err int32

const (
	Err_OK           Err = 0
	Err_WRONG_LEADER Err = 1
	Err_TIMEOUT      Err = 2
)

// Enum value maps for Err.
var (
	Err_name = map[int32]string{
		0: "OK",
		1: "WRONG_LEADER",
		2: "TIMEOUT",
	}
	Err_value = map[string]int32{
		"OK":           0,
		"WRONG_LEADER": 1,
		"TIMEOUT":      2,
	}
)

func (x Err) Enum() *Err {
	p := new(Err)
	*p = x
	return p
}

func (x Err) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Err) Descriptor() protoreflect.EnumDescriptor {
	return file_ctrl_proto_enumTypes[1].Descriptor()
}

func (Err) Type() protoreflect.EnumType {
	return &file_ctrl_proto_enumTypes[1]
}

func (x Err) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Err.Descriptor instead.
func (Err) EnumDescriptor() ([]byte, []int) {
	return file_ctrl_proto_rawDescGZIP(), []int{1}
}

type Servers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int32                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Servers) Reset() {
	*x = Servers{}
	mi := &file_ctrl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Servers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Servers) ProtoMessage() {}

func (x *Servers) ProtoReflect() protoreflect.Message {
	mi := &file_ctrl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Servers.ProtoReflect.Descriptor instead.
func (*Servers) Descriptor() ([]byte, []int) {
	return file_ctrl_proto_rawDescGZIP(), []int{0}
}

func (x *Servers) GetIds() []int32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

// Config is one numbered assignment of shards to replica groups.
type Config struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Num    uint64                 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	Shards []int64                `protobuf:"varint,2,rep,packed,name=shards,proto3" json:"shards,omitempty"` // shard index -> group ID (0 = unassigned)
	Groups map[int64]*Servers     `protobuf:"bytes,3,rep,name=groups,proto3" json:"groups,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// pinned records shards moved explicitly with Move; the ring does not
	// reassign them while their group exists.
	Pinned        map[int32]int64 `protobuf:"bytes,4,rep,name=pinned,proto3" json:"pinned,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_ctrl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_ctrl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_ctrl_proto_rawDescGZIP(), []int{1}
}

func (x *Config) GetNum() uint64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *Config) GetShards() []int64 {
	if x != nil {
		return x.Shards
	}
	return nil
}

func (x *Config) GetGroups() map[int64]*Servers {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *Config) GetPinned() map[int32]int64 {
	if x != nil {
		return x.Pinned
	}
	return nil
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            Op                     `protobuf:"varint,1,opt,name=op,proto3,enum=strata.ctrl.Op" json:"op,omitempty"`
	Join          map[int64]*Servers     `protobuf:"bytes,2,rep,name=join,proto3" json:"join,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Leave         []int64                `protobuf:"varint,3,rep,packed,name=leave,proto3" json:"leave,omitempty"`
	Shard         int32                  `protobuf:"varint,4,opt,name=shard,proto3" json:"shard,omitempty"`
	Gid           int64                  `protobuf:"varint,5,opt,name=gid,proto3" json:"gid,omitempty"`
	Num           int64                  `protobuf:"varint,6,opt,name=num,proto3" json:"num,omitempty"` // QUERY: config number, or -1 / beyond latest for the latest
	ClientId      uint64                 `protobuf:"varint,7,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,8,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_ctrl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_ctrl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_ctrl_proto_rawDescGZIP(), []int{2}
}

func (x *Request) GetOp() Op {
	if x != nil {
		return x.Op
	}
	return Op_QUERY
}

func (x *Request) GetJoin() map[int64]*Servers {
	if x != nil {
		return x.Join
	}
	return nil
}

func (x *Request) GetLeave() []int64 {
	if x != nil {
		return x.Leave
	}
	return nil
}

func (x *Request) GetShard() int32 {
	if x != nil {
		return x.Shard
	}
	return 0
}

func (x *Request) GetGid() int64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *Request) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *Request) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *Request) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           Err                    `protobuf:"varint,1,opt,name=err,proto3,enum=strata.ctrl.Err" json:"err,omitempty"`
	Config        *Config                `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	LeaderHint    int32                  `protobuf:"varint,3,opt,name=leader_hint,json=leaderHint,proto3" json:"leader_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_ctrl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_ctrl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_ctrl_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetErr() Err {
	if x != nil {
		return x.Err
	}
	return Err_OK
}

func (x *Response) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Response) GetLeaderHint() int32 {
	if x != nil {
		return x.LeaderHint
	}
	return 0
}

var File_ctrl_proto protoreflect.FileDescriptor

const file_ctrl_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"ctrl.proto\x12\vstrata.ctrl\"\x1b\n" +
	"\aServers\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x05R\x03ids\"\xb0\x02\n" +
	"\x06Config\x12\x10\n" +
	"\x03num\x18\x01 \x01(\x04R\x03num\x12\x16\n" +
	"\x06shards\x18\x02 \x03(\x03R\x06shards\x127\n" +
	"\x06groups\x18\x03 \x03(\v2\x1f.strata.ctrl.Config.GroupsEntryR\x06groups\x127\n" +
	"\x06pinned\x18\x04 \x03(\v2\x1f.strata.ctrl.Config.PinnedEntryR\x06pinned\x1aO\n" +
	"\vGroupsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.strata.ctrl.ServersR\x05value:\x028\x01\x1a9\n" +
	"\vPinnedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xac\x02\n" +
	"\aRequest\x12\x1f\n" +
	"\x02op\x18\x01 \x01(\x0e2\x0f.strata.ctrl.OpR\x02op\x122\n" +
	"\x04join\x18\x02 \x03(\v2\x1e.strata.ctrl.Request.JoinEntryR\x04join\x12\x14\n" +
	"\x05leave\x18\x03 \x03(\x03R\x05leave\x12\x14\n" +
	"\x05shard\x18\x04 \x01(\x05R\x05shard\x12\x10\n" +
	"\x03gid\x18\x05 \x01(\x03R\x03gid\x12\x10\n" +
	"\x03num\x18\x06 \x01(\x03R\x03num\x12\x1b\n" +
	"\tclient_id\x18\a \x01(\x04R\bclientId\x12\x10\n" +
	"\x03seq\x18\b \x01(\x04R\x03seq\x1aM\n" +
	"\tJoinEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.strata.ctrl.ServersR\x05value:\x028\x01\"|\n" +
	"\bResponse\x12\"\n" +
	"\x03err\x18\x01 \x01(\x0e2\x10.strata.ctrl.ErrR\x03err\x12+\n" +
	"\x06config\x18\x02 \x01(\v2\x13.strata.ctrl.ConfigR\x06config\x12\x1f\n" +
	"\vleader_hint\x18\x03 \x01(\x05R\n" +
	"leaderHint*.\n" +
	"\x02Op\x12\t\n" +
	"\x05QUERY\x10\x00\x12\b\n" +
	"\x04JOIN\x10\x01\x12\t\n" +
	"\x05LEAVE\x10\x02\x12\b\n" +
	"\x04MOVE\x10\x03*,\n" +
	"\x03Err\x12\x06\n" +
	"\x02OK\x10\x00\x12\x10\n" +
	"\fWRONG_LEADER\x10\x01\x12\v\n" +
	"\aTIMEOUT\x10\x022?\n" +
	"\n" +
	"Controller\x121\n" +
	"\x02Do\x12\x14.strata.ctrl.Request\x1a\x15.strata.ctrl.ResponseB)Z'github.com/HridhayP/strata/proto/ctrlpbb\x06proto3"

var (
	file_ctrl_proto_rawDescOnce sync.Once
	file_ctrl_proto_rawDescData []byte
)

func file_ctrl_proto_rawDescGZIP() []byte {
	file_ctrl_proto_rawDescOnce.Do(func() {
		file_ctrl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ctrl_proto_rawDesc), len(file_ctrl_proto_rawDesc)))
	})
	return file_ctrl_proto_rawDescData
}

var file_ctrl_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ctrl_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_ctrl_proto_goTypes = []any{
	(Op)(0),          // 0: strata.ctrl.Op
	(Err)(0),         // 1: strata.ctrl.Err
	(*Servers)(nil),  // 2: strata.ctrl.Servers
	(*Config)(nil),   // 3: strata.ctrl.Config
	(*Request)(nil),  // 4: strata.ctrl.Request
	(*Response)(nil), // 5: strata.ctrl.Response
	nil,              // 6: strata.ctrl.Config.GroupsEntry
	nil,              // 7: strata.ctrl.Config.PinnedEntry
	nil,              // 8: strata.ctrl.Request.JoinEntry
}
var file_ctrl_proto_depIdxs = []int32{
	6, // 0: strata.ctrl.Config.groups:type_name -> strata.ctrl.Config.GroupsEntry
	7, // 1: strata.ctrl.Config.pinned:type_name -> strata.ctrl.Config.PinnedEntry
	0, // 2: strata.ctrl.Request.op:type_name -> strata.ctrl.Op
	8, // 3: strata.ctrl.Request.join:type_name -> strata.ctrl.Request.JoinEntry
	1, // 4: strata.ctrl.Response.err:type_name -> strata.ctrl.Err
	3, // 5: strata.ctrl.Response.config:type_name -> strata.ctrl.Config
	2, // 6: strata.ctrl.Config.GroupsEntry.value:type_name -> strata.ctrl.Servers
	2, // 7: strata.ctrl.Request.JoinEntry.value:type_name -> strata.ctrl.Servers
	4, // 8: strata.ctrl.Controller.Do:input_type -> strata.ctrl.Request
	5, // 9: strata.ctrl.Controller.Do:output_type -> strata.ctrl.Response
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_ctrl_proto_init() }
func file_ctrl_proto_init() {
	if File_ctrl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ctrl_proto_rawDesc), len(file_ctrl_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ctrl_proto_goTypes,
		DependencyIndexes: file_ctrl_proto_depIdxs,
		EnumInfos:         file_ctrl_proto_enumTypes,
		MessageInfos:      file_ctrl_proto_msgTypes,
	}.Build()
	File_ctrl_proto = out.File
	file_ctrl_proto_goTypes = nil
	file_ctrl_proto_depIdxs = nil
}
