// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: kv.proto

package kvpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Op int32

const (
	Op_GET    Op = 0
	Op_PUT    Op = 1
	Op_APPEND Op = 2
)

// Enum value maps for Op.
var (
	Op_name = map[int32]string{
		0: "GET",
		1: "PUT",
		2: "APPEND",
	}
	Op_value = map[string]int32{
		"GET":    0,
		"PUT":    1,
		"APPEND": 2,
	}
)

func (x Op) Enum() *Op {
	p := new(Op)
	*p = x
	return p
}

func (x Op) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Op) Descriptor() protoreflect.EnumDescriptor {
	return file_kv_proto_enumTypes[0].Descriptor()
}

func (Op) Type() protoreflect.EnumType {
	return &file_kv_proto_enumTypes[0]
}

func (x Op) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Op.Descriptor instead.
func (Op) EnumDescriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{0}
}

type Err int32

const (
	Err_OK           Err = 0
	Err_NO_KEY       Err = 1
	Err_WRONG_LEADER Err = 2
	Err_WRONG_GROUP  Err = 3 // this replica group does not own the key's shard
	Err_TIMEOUT      Err = 4
)

// Enum value maps for Err.
var (
	Err_name = map[int32]string{
		0: "OK",
		1: "NO_KEY",
		2: "WRONG_LEADER",
		3: "WRONG_GROUP",
		4: "TIMEOUT",
	}
	Err_value = map[string]int32{
		"OK":           0,
		"NO_KEY":       1,
		"WRONG_LEADER": 2,
		"WRONG_GROUP":  3,
		"TIMEOUT":      4,
	}
)

func (x Err) Enum() *Err {
	p := new(Err)
	*p = x
	return p
}

func (x Err) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Err) Descriptor() protoreflect.EnumDescriptor {
	return file_kv_proto_enumTypes[1].Descriptor()
}

func (Err) Type() protoreflect.EnumType {
	return &file_kv_proto_enumTypes[1]
}

func (x Err) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Err.Descriptor instead.
func (Err) EnumDescriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{1}
}

type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Group string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"` // routing key when one process hosts several groups
	Op    Op                     `protobuf:"varint,2,opt,name=op,proto3,enum=strata.kv.Op" json:"op,omitempty"`
	Key   string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	// (client_id, seq) identifies a write so retries are applied at most once.
	ClientId      uint64 `protobuf:"varint,5,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Seq           uint64 `protobuf:"varint,6,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_kv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Request) GetOp() Op {
	if x != nil {
		return x.Op
	}
	return Op_GET
}

func (x *Request) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Request) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Request) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *Request) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           Err                    `protobuf:"varint,1,opt,name=err,proto3,enum=strata.kv.Err" json:"err,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	LeaderHint    int32                  `protobuf:"varint,3,opt,name=leader_hint,json=leaderHint,proto3" json:"leader_hint,omitempty"` // -1 if unknown
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_kv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetErr() Err {
	if x != nil {
		return x.Err
	}
	return Err_OK
}

func (x *Response) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Response) GetLeaderHint() int32 {
	if x != nil {
		return x.LeaderHint
	}
	return 0
}

// Command is what the KV state machine stores in the Raft log.
type Command struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Cmd:
	//
	//	*Command_Client
	Cmd           isCommand_Cmd `protobuf_oneof:"cmd"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_kv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{2}
}

func (x *Command) GetCmd() isCommand_Cmd {
	if x != nil {
		return x.Cmd
	}
	return nil
}

func (x *Command) GetClient() *Request {
	if x != nil {
		if x, ok := x.Cmd.(*Command_Client); ok {
			return x.Client
		}
	}
	return nil
}

type isCommand_Cmd interface {
	isCommand_Cmd()
}

type Command_Client struct {
	Client *Request `protobuf:"bytes,1,opt,name=client,proto3,oneof"`
}

func (*Command_Client) isCommand_Cmd() {}

var File_kv_proto protoreflect.FileDescriptor

const file_kv_proto_rawDesc = "" +
	"\n" +
	"\bkv.proto\x12\tstrata.kv\"\x95\x01\n" +
	"\aRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x1d\n" +
	"\x02op\x18\x02 \x01(\x0e2\r.strata.kv.OpR\x02op\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x04 \x01(\fR\x05value\x12\x1b\n" +
	"\tclient_id\x18\x05 \x01(\x04R\bclientId\x12\x10\n" +
	"\x03seq\x18\x06 \x01(\x04R\x03seq\"c\n" +
	"\bResponse\x12 \n" +
	"\x03err\x18\x01 \x01(\x0e2\x0e.strata.kv.ErrR\x03err\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1f\n" +
	"\vleader_hint\x18\x03 \x01(\x05R\n" +
	"leaderHint\">\n" +
	"\aCommand\x12,\n" +
	"\x06client\x18\x01 \x01(\v2\x12.strata.kv.RequestH\x00R\x06clientB\x05\n" +
	"\x03cmd*\"\n" +
	"\x02Op\x12\a\n" +
	"\x03GET\x10\x00\x12\a\n" +
	"\x03PUT\x10\x01\x12\n" +
	"\n" +
	"\x06APPEND\x10\x02*I\n" +
	"\x03Err\x12\x06\n" +
	"\x02OK\x10\x00\x12\n" +
	"\n" +
	"\x06NO_KEY\x10\x01\x12\x10\n" +
	"\fWRONG_LEADER\x10\x02\x12\x0f\n" +
	"\vWRONG_GROUP\x10\x03\x12\v\n" +
	"\aTIMEOUT\x10\x0423\n" +
	"\x02KV\x12-\n" +
	"\x02Do\x12\x12.strata.kv.Request\x1a\x13.strata.kv.ResponseB'Z%github.com/HridhayP/strata/proto/kvpbb\x06proto3"

var (
	file_kv_proto_rawDescOnce sync.Once
	file_kv_proto_rawDescData []byte
)

func file_kv_proto_rawDescGZIP() []byte {
	file_kv_proto_rawDescOnce.Do(func() {
		file_kv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kv_proto_rawDesc), len(file_kv_proto_rawDesc)))
	})
	return file_kv_proto_rawDescData
}

var file_kv_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_kv_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kv_proto_goTypes = []any{
	(Op)(0),          // 0: strata.kv.Op
	(Err)(0),         // 1: strata.kv.Err
	(*Request)(nil),  // 2: strata.kv.Request
	(*Response)(nil), // 3: strata.kv.Response
	(*Command)(nil),  // 4: strata.kv.Command
}
var file_kv_proto_depIdxs = []int32{
	0, // 0: strata.kv.Request.op:type_name -> strata.kv.Op
	1, // 1: strata.kv.Response.err:type_name -> strata.kv.Err
	2, // 2: strata.kv.Command.client:type_name -> strata.kv.Request
	2, // 3: strata.kv.KV.Do:input_type -> strata.kv.Request
	3, // 4: strata.kv.KV.Do:output_type -> strata.kv.Response
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_kv_proto_init() }
func file_kv_proto_init() {
	if File_kv_proto != nil {
		return
	}
	file_kv_proto_msgTypes[2].OneofWrappers = []any{
		(*Command_Client)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kv_proto_rawDesc), len(file_kv_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kv_proto_goTypes,
		DependencyIndexes: file_kv_proto_depIdxs,
		EnumInfos:         file_kv_proto_enumTypes,
		MessageInfos:      file_kv_proto_msgTypes,
	}.Build()
	File_kv_proto = out.File
	file_kv_proto_goTypes = nil
	file_kv_proto_depIdxs = nil
}
